apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: postgis-l2-policy
spec:
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: postgis-external
  interfaces:
    - ^enp9s0$
  externalIPs: false
  loadBalancerIPs: true