# Reserved LAN IP address pool for LoadBalancer Services
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: lan-ip-pool
spec:
  blocks:
    - start: "${GATEWAY_IP}"
      stop: "192.0.2.250"
