# L2 announcement policy for LoadBalancer Services on the LAN interface
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lan-l2-policy
spec:
  interfaces:
    - "^${LAN_INTERFACE}$"
  externalIPs: false
  loadBalancerIPs: true
