---
opentofu_binary: /usr/local/bin/tofu
opentofu_rotate_vault_secrets: false
opentofu_secrets_dir: "{{ ansible_facts.env.HOME }}/.config/data_science_cluster"
opentofu_secrets_wo_version_file: "{{ opentofu_secrets_dir }}/vault-secrets-wo-version"
