apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-credentials
  namespace: databases
spec:
  refreshInterval: ${ESO_REFRESH_INTERVAL}
  secretStoreRef:
    kind: SecretStore
    name: openbao
  target:
    name: seaweedfs-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: seaweedfs
