# Helm values for in-cluster HashiCorp Vault

global:
  tlsDisable: false

injector:
  enabled: false

server:
  image:
    repository: "hashicorp/vault"
    tag: "${VAULT_IMAGE_TAG}"
  resources:
    requests:
      cpu: ${VAULT_CPU_REQUEST}
      memory: ${VAULT_MEM_REQUEST}
    limits:
      memory: ${VAULT_MEM_LIMIT}
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-cert/ca.crt

  extraVolumes:
    - type: secret
      name: vault-server-cert

  standalone:
    enabled: true
    config: |
      disable_mlock = true
      ui = true

      listener "tcp" {
        address          = "[::]:8200"
        cluster_address  = "[::]:8201"
        tls_cert_file    = "/vault/userconfig/vault-server-cert/tls.crt"
        tls_key_file     = "/vault/userconfig/vault-server-cert/tls.key"
      }

      storage "file" {
        path = "/vault/data"
      }