---
- name: The k3s config on a fresh host
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Run the k3s role's config tasks
      ansible.builtin.import_role:
        name: data_science.cluster.k3s
        tasks_from: config
