---
all:
  children:
    molecule:
      hosts:
        data-cluster-test:
      vars:
        ansible_connection: containers.podman.podman
        container_image: registry.access.redhat.com/ubi9/ubi-init:latest
        container_command: /sbin/init
        container_systemd: always
        container_volumes:
          - "{{ repo_root }}:{{ repo_root }}:ro"
        container_cap_add:
          - NET_ADMIN
        container_security_opt:
          - label=disable
