apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-secrets-ingress
  namespace: external-secrets
spec:
  endpointSelector: {}
  ingress:
    # Admission webhook
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
