apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/external-secrets/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "${ESO_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  values:
    installCRDs: true
    resources:
      requests:
        cpu: ${ESO_CPU_REQUEST}
        memory: ${ESO_MEM_REQUEST}
      limits:
        memory: ${ESO_MEM_LIMIT}
    webhook:
      resources:
        requests:
          cpu: ${ESO_WEBHOOK_CPU_REQUEST}
          memory: ${ESO_WEBHOOK_MEM_REQUEST}
        limits:
          memory: ${ESO_WEBHOOK_MEM_LIMIT}
    certController:
      resources:
        requests:
          cpu: ${ESO_CERT_CONTROLLER_CPU_REQUEST}
          memory: ${ESO_CERT_CONTROLLER_MEM_REQUEST}
        limits:
          memory: ${ESO_CERT_CONTROLLER_MEM_LIMIT}
