---
- name: "Install Gateway API Custom Resource Definitions (CRDs) {{ gateway_api_version }}"
  kubernetes.core.k8s:
    state: present
    src: "{{ repo_root }}/infrastructure/gateway-api-crds/standard-install.yaml"
    server_side_apply:
      field_manager: ansible
