---
- name: Add Hashicorp apt repo key
  ansible.builtin.shell:
    cmd: curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Add Hashicorp apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present
    filename: hashicorp
  become: true

- name: Install Vault
  ansible.builtin.apt:
    name: vault
    state: present
    update_cache: true
  become: true
