---
- name: Create /etc/rancher/k3s directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    mode: "0755"
    state: directory
  become: true

- name: Write k3s config.yaml
  ansible.builtin.copy:
    dest: /etc/rancher/k3s/config.yaml
    mode: "0644"
    content: |
      write-kubeconfig-mode: "0644"
      write-kubeconfig: "{{ kubeconfig_path }}"
      disable:
        - traefik
        - servicelb
      disable-kube-proxy: true
      disable-network-policy: true
      flannel-backend: none
      secrets-encryption: true
  become: true
