---
- name: Provision k3s Data Science Cluster
  hosts: localhost
  become: false

  roles:
    - { role: k3s, tags: [k3s, bootstrap] }
    - { role: cilium, tags: [cilium, bootstrap] }
    - { role: opentofu, tags: [vault, bootstrap]}
    - { role: vault, tags: [vault, bootstrap]}
    - { role: fluxcd, tags: [flux, bootstrap]}