apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  values:
    resources:
      requests:
        cpu: 2m
        memory: 200Mi
      limits:
        memory: 600Mi
  interval: 1h
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.29.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg