apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnpg-egress
  namespace: cnpg-system
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cnpg
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: databases
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP