apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
  namespace: cnpg-system
spec:
  values:
    resources:
      requests:
        cpu: ${BARMAN_CLOUD_CPU_REQUEST}
        memory: ${BARMAN_CLOUD_MEM_REQUEST}
      limits:
        memory: ${BARMAN_CLOUD_MEM_LIMIT}
  interval: 1h
  releaseName: plugin-barman-cloud
  chart:
    spec:
      chart: plugin-barman-cloud
      version: "${BARMAN_CLOUD_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
