apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vso-setup.yaml
  - postgres-tls.yaml
  - postgis-cluster.yaml
  - postgis-external-service.yaml
  - postgis-database.yaml
  - seaweedfs-release.yaml
  - seaweedfs-credentials.yaml
  - seaweedfs-networkpolicy.yaml