apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vso-setup.yaml
  - postgis-tls.yaml
  - postgis-cluster.yaml
  - postgis-tcproute.yaml
  - postgis-database.yaml
  - seaweedfs-release.yaml
  - seaweedfs-credentials.yaml
  - seaweedfs-networkpolicy.yaml