apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs
  namespace: databases
spec:
  interval: 24h
  url: https://seaweedfs.github.io/seaweedfs/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: databases
spec:
  interval: 1h
  releaseName: seaweedfs
  chart:
    spec:
      chart: seaweedfs
      version: "4.40.0"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
  values:
    master:
      ipBind: "0.0.0.0"
    filer:
      ipBind: "0.0.0.0"
    volume:
      dataDirs:
        - name: data1
          type: "hostPath"
          hostPathPrefix: "/mnt/vault13/seaweedfs"
          maxVolumes: 90
    s3:
      enabled: true
      port: 9000
      createBuckets:
        - name: cnpg-backups
      extraArgs:
        - "-cert.file=/var/run/secrets/spiffe.io/tls.crt"
        - "-key.file=/var/run/secrets/spiffe.io/tls.key"
      extraVolumeMounts: |
        - name: spiffe
          mountPath: /var/run/secrets/spiffe.io
          readOnly: true
      extraVolumes: |
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true