apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: seaweedfs-vault-secret
  namespace: databases
spec:
  type: kv-v2
  mount: secret
  path: seaweedfs
  destination:
    name: seaweedfs-credentials
    create: true
  refreshAfter: 1h
  vaultAuthRef: vault-auth
