apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs
  namespace: databases
spec:
  interval: 24h
  url: https://seaweedfs.github.io/seaweedfs/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
  namespace: databases
spec:
  interval: 1h
  releaseName: seaweedfs
  chart:
    spec:
      chart: seaweedfs
      version: "${SEAWEEDFS_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
  values:
    master:
      ipBind: "0.0.0.0"
    filer:
      ipBind: "0.0.0.0"
    volume:
      dataDirs:
        - name: data1
          type: "hostPath"
          hostPathPrefix: "/mnt/vault13/seaweedfs"
          maxVolumes: 90
    s3:
      enabled: true
      port: 9000
      createBuckets:
        - name: cnpg-backups
      livenessProbe:
        httpGet:
          scheme: HTTPS
      readinessProbe:
        httpGet:
          scheme: HTTPS
      # S3 TLS certificates provisioned via cert-manager seaweedfs-s3-tls Certificate
      # backed by vault-pki-issuer.
      extraArgs:
        - "-cert.file=/var/run/secrets/seaweedfs.io/tls.crt"
        - "-key.file=/var/run/secrets/seaweedfs.io/tls.key"
        - "-config=/var/run/secrets/seaweedfs-config/config"
      extraVolumeMounts: |
        - name: seaweedfs-tls
          mountPath: /var/run/secrets/seaweedfs.io
          readOnly: true
        - name: seaweedfs-config
          mountPath: /var/run/secrets/seaweedfs-config
          readOnly: true
      extraVolumes: |
        - name: seaweedfs-tls
          secret:
            secretName: seaweedfs-s3-tls
        - name: seaweedfs-config
          secret:
            secretName: seaweedfs-credentials