# Restricts egress to kube-dns on port 53, and databases namespace
# Restricts ingress to databases namespace
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: seaweedfs-ingress-egress
  namespace: databases
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
  ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: databases
  egress:
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: kube-system
          k8s-app: kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: UDP
          - port: "53"
            protocol: TCP
    - toEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: databases
