apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 24h
  type: oci
  url: oci://quay.io/jetstack/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 1h
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "${CERT_MANAGER_VERSION}"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    resources:
      requests:
        cpu: ${CERT_MANAGER_CPU_REQUEST}
        memory: ${CERT_MANAGER_MEM_REQUEST}
      limits:
        memory: ${CERT_MANAGER_MEM_LIMIT}
    webhook:
      resources:
        requests:
          cpu: ${CERT_MANAGER_WEBHOOK_CPU_REQUEST}
          memory: ${CERT_MANAGER_WEBHOOK_MEM_REQUEST}
        limits:
          memory: ${CERT_MANAGER_WEBHOOK_MEM_LIMIT}
    cainjector:
      resources:
        requests:
          cpu: ${CERT_MANAGER_CAINJECTOR_CPU_REQUEST}
          memory: ${CERT_MANAGER_CAINJECTOR_MEM_REQUEST}
        limits:
          memory: ${CERT_MANAGER_CAINJECTOR_MEM_LIMIT}
    startupapicheck:
      resources:
        requests:
          cpu: ${CERT_MANAGER_STARTUPAPICHECK_CPU_REQUEST}
          memory: ${CERT_MANAGER_STARTUPAPICHECK_MEM_REQUEST}
        limits:
          memory: ${CERT_MANAGER_STARTUPAPICHECK_MEM_LIMIT}
    crds:
      enabled: true
