---
namespace: data_science
name: cluster
version: 1.2.0
readme: README.md
authors:
  - DragonBishop
description: Roles and playbooks that bootstrap the data science cluster.
license:
  - MIT
tags:
  - infrastructure
repository: https://github.com/DragonBishop/data_science_cluster
dependencies:
  kubernetes.core: ">=6.5.0"
  cloud.terraform: ">=4.0.0"
