# Postgres database names.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  DATA_SCIENCE_DB_NAME: "data_science"
  TEKTON_RESULTS_DB_NAME: "tekton_results"
