apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-config.yaml
patches:
  - path: versions.yaml
  - path: networking.yaml
  - path: cpu-memory.yaml
  - path: storage.yaml
  - path: databases.yaml
  - path: replicas.yaml
  - path: certificates.yaml
  - path: schedules.yaml
  - path: retention.yaml
  - path: timeouts.yaml
