---
- name: Initialize OpenBao
  when: not (openbao_status_result.stdout | from_json).initialized
  block:
    - name: Initialize in-cluster OpenBao
      kubernetes.core.k8s_exec:
        namespace: "{{ openbao_namespace }}"
        pod: "{{ openbao_pod }}"
        command: bao operator init -format=json
      register: openbao_init_result
      no_log: true

    - name: Parse OpenBao init output
      ansible.builtin.set_fact:
        openbao_root_token: "{{ (openbao_init_result.stdout | from_json).root_token }}"
        openbao_fresh_unseal_keys: "{{ (openbao_init_result.stdout | from_json).unseal_keys_b64[:3] }}"
      no_log: true
