# Cilium Helm values for Hubble Relay
hubble:
  relay:
    resources:
      requests:
        memory: ${HUBBLE_RELAY_MEM_REQUEST}
      limits:
        memory: ${HUBBLE_RELAY_MEM_LIMIT}
    enabled: true
    tls:
      server:
        enabled: true
        mtls: true
  ui:
    enabled: false
  tls:
    auto:
      enabled: true
      method: certmanager
      certValidityDuration: ${HUBBLE_CERT_VALIDITY_DAYS}
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: openbao-pki-issuer
