# Cilium Helm values for Hubble Relay and UI
hubble:
  relay:
    resources:
      requests:
        memory: 70Mi
      limits:
        memory: 100Mi
    enabled: true
    tls:
      server:
        enabled: true
        mtls: true
  ui:
    frontend:
      resources:
        requests:
          memory: 25Mi
        limits:
          memory: 40Mi
    backend:
      resources:
        requests:
          memory: 70Mi
        limits:
          memory: 100Mi
    enabled: true
  tls:
    auto:
      enabled: true
      method: certmanager
      certManagerIssuerRef:
        group: cert-manager.io
        kind: ClusterIssuer
        name: vault-pki-issuer
