apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hubble-httproute.yaml
configMapGenerator:
  - name: cilium-values-hubble
    namespace: kube-system
    files:
      - values.yaml=cilium-values-hubble.yaml
generatorOptions:
  disableNameSuffixHash: true
