apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hubble-networkpolicy.yaml
  - hubble-localhost.yaml
configMapGenerator:
  - name: cilium-values-hubble
    namespace: kube-system
    files:
      - values.yaml=cilium-values-hubble.yaml
    options:
      disableNameSuffixHash: true
      labels:
        reconcile.fluxcd.io/watch: Enabled
